master_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from master_project import views
from rest_framework.routers import DefaultRouter
from master.views import ServiceViewSet, AppointmentViewSet, AgendamentoViewSet, UserViewSet
from user.views import prestadores_por_categoria, logout_view
from user import views as user_views
from avaliacao.urls import AvaliacaoCreateView


router = DefaultRouter()
router.register(r'services', ServiceViewSet, basename='service') 
router.register(r'apontamentos', AppointmentViewSet, basename='apontamentos')
router.register(r'agendamentos', AgendamentoViewSet, basename='agendamentos')
router.register(r'usuarios', UserViewSet, basename='usuarios')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('api/', include(router.urls)),
    path('agendamentos/', include('user.urls', namespace='agendamentos')),
    path('avaliacao/', include('avaliacao.urls')),

    
    
    
    # URLs de Login e Logout
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', logout_view, name='logout'),



    # Cadastro de usuário
    path('register/', user_views.register, name='register'),
    path('prestadores/categoria/<int:categoria_id>/', prestadores_por_categoria, name='prestadores_por_categoria'),
    
   
]

user/urls.py
from user.views import AgendamentoCreate,AgendamentosListView, UsuariosListView, Novousuario, AgendamentoDelete, AgendamentoDetail, AgendamentosUpdateView, AgendamentoCreateView
from django.urls import path
 
app_name = 'agendamentos' 
 
urlpatterns = [
 # URLs para Agendamentos
    path('', AgendamentosListView.as_view(), name='agendamentos-list'),
    path('novo/', AgendamentoCreate.as_view(), name='agendamento-create'),
    path('delete/<int:pk>/', AgendamentoDelete.as_view(), name='deleteagendamento'),
    path('<int:pk>/', AgendamentoDetail.as_view(), name='agendamentodetail'),
    path('<int:pk>/editar/', AgendamentosUpdateView.as_view(), name='agendamentosupdate'),
    path('novo/<int:prestador_id>/', AgendamentoCreateView.as_view(), name='agendamento-create'),
    
    
    path('usuarios', UsuariosListView.as_view(), name='usuarios-list'),
    path('usuarios/novo/', Novousuario.as_view(), name='usuario-create'),

    ]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db import models


class User(AbstractUser):
    tipo_usuario = models.CharField(max_length=10, choices=[('prestador', 'Prestador'), ('cliente', 'Cliente')])
    foto = models.ImageField(upload_to='fotos_perfil/', blank=True, null=True)

    def __str__(self):
        return self.username

    def get_servicos(self):
        from master.models import Servicos  # Importação atrasada
        return Servicos


class Perfil(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    biografia = models.TextField(blank=True, null=True)
    localizacao = models.CharField(max_length=100, blank=True, null=True)
    avaliacao_media = models.FloatField(default=0.0)

    def __str__(self):
        return f'Perfil de {self.usuario.username}'

    class Meta:
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfis'



class Agendamento(models.Model):
    STATUS_CHOICES = [
        ('confirmado', 'Confirmado'),
        ('cancelado', 'Cancelado'),
        ('pendente', 'Pendente'),
    ]

    id = models.BigAutoField(primary_key=True)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    servico = models.ForeignKey('master.Servicos', on_delete=models.CASCADE)  
    data = models.DateField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pendente', null=True, blank=True)
    remetente = models.ForeignKey(User, related_name='mensagens_enviadas', on_delete=models.CASCADE)
    destinatario = models.ForeignKey(User, related_name='mensagens_recebidas', on_delete=models.CASCADE, null=True, blank=True)
    conteudo = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.servico} - {self.data} - {self.status}"

user/forms.py
from django import forms
from .models import Agendamento, User
from master.models import Categoria, Especialidade, Servicos, Grupo
from django.contrib.auth.forms import UserCreationForm


class AgendamentoForm(forms.ModelForm):
    class Meta:
        model = Agendamento
        exclude = ['remetente', 'usuario']  
        widgets = {
            
            'servico': forms.Select(attrs={'class': 'form-control'}),
            'data': forms.DateInput(attrs={
                'class': 'form-control',
                'type': 'date'
            }, format='%Y-%m-%d'),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'destinatario': forms.Select(attrs={'class': 'form-control'}),
            'conteudo': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3,
                'placeholder': 'Escreva sua mensagem aqui...'
            }),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Filtra usuários com tipo 'prestador'
        self.fields['destinatario'].queryset = User.objects.filter(tipo_usuario='prestador')
    
        

class CustomUserCreationForm(UserCreationForm):
    # Campos do modelo de usuário
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'foto', 'tipo_usuario')

    # Campos de serviço
    titulo_servico = forms.CharField(required=False, label="Título do Serviço")
    categoria_servico = forms.ModelChoiceField(queryset=Categoria.objects.all(), required=False, label="Categoria")
    grupo_servico = forms.ModelChoiceField(queryset=Grupo.objects.all(), required=False, label="Grupo")
    especialidade_servico = forms.ModelChoiceField(queryset=Especialidade.objects.all(), required=False, label="Especialidade")

    def clean(self):
        cleaned_data = super().clean()
        tipo_usuario = cleaned_data.get('tipo_usuario')

        # Validação: Se o tipo de usuário é 'prestador', os campos de serviço são obrigatórios
        if tipo_usuario == 'prestador':
            if not cleaned_data.get('titulo_servico'):
                self.add_error('titulo_servico', 'Este campo é obrigatório para prestadores.')
            if not cleaned_data.get('categoria_servico'):
                self.add_error('categoria_servico', 'Selecione uma categoria.')
            if not cleaned_data.get('grupo_servico'):
                self.add_error('grupo_servico', 'Selecione um grupo.')
            if not cleaned_data.get('especialidade_servico'):
                self.add_error('especialidade_servico', 'Selecione uma especialidade.')

    def save(self, commit=True):
        user = super().save(commit=False)

        # Salvando o usuário sem commit para ajustar o serviço depois
        if commit:
            user.save()

        # Salvando o serviço associado, se o usuário for um prestador
        if user.tipo_usuario == 'prestador':
            Servicos.objects.create(
                titulo=self.cleaned_data['titulo_servico'],
                categoria=self.cleaned_data['categoria_servico'],
                grupo=self.cleaned_data['grupo_servico'],
                especialidade=self.cleaned_data['especialidade_servico'],
                prestador=user
            )

        return user

user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import login, logout as auth_logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from master.models import Categoria, Servicos
from .models import Agendamento, User
from .forms import AgendamentoForm, CustomUserCreationForm




# Views de Usuários
class UsuariosListView(ListView):
    model = User
    template_name = 'usuarios.html'
    context_object_name = 'usuarios'

    # Filtros (descomentado se necessário)
    def get_queryset(self):
        users = super().get_queryset().order_by('username')  # Altere 'username' se necessário
        search = self.request.GET.get('search')
        if search:
            users = users.filter(username__icontains=search)
        return users




class Novousuario(CreateView):
    model = User
    form_class = CustomUserCreationForm  
    template_name = 'novousuario.html'
    success_url = reverse_lazy('usuarios')
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.save()

        # Associar serviços se o usuário for prestador
        if user.tipo_usuario == 'prestador':
            # Crie o objeto de serviço
            Servicos.objects.create(
                titulo=form.cleaned_data['titulo_servico'],
                categoria=form.cleaned_data['categoria_servico'],
                grupo=form.cleaned_data['grupo_servico'],
                especialidade=form.cleaned_data['especialidade_servico']
                # Associe o serviço ao usuário se necessário
            )

        return super().form_valid(form)


# Views de Agendamento
class AgendamentosListView(LoginRequiredMixin, ListView):
    model = Agendamento
    template_name = 'agendamentos.html'
    context_object_name = 'agendamentos'

    def get_queryset(self):
       
        return Agendamento.objects.filter(remetente=self.request.user) | Agendamento.objects.filter(destinatario=self.request.user)


class AgendamentoCreate(LoginRequiredMixin, CreateView):
    model = Agendamento
    form_class = AgendamentoForm
    template_name = 'createagendamento.html'
    success_url = reverse_lazy('agendamentos:agendamentos-list')

    def form_valid(self, form):
        form.instance.remetente = self.request.user
        form.instance.usuario = self.request.user
        messages.success(self.request, "Agendamento criado com sucesso!")  # Mensagem de sucesso
        return super().form_valid(form)


class AgendamentoCreateView(LoginRequiredMixin, CreateView):
    model = Agendamento
    form_class = AgendamentoForm
    template_name = 'createagendamento.html'
    success_url = reverse_lazy('agendamentos:agendamentos-list')

    def form_valid(self, form):
        form.instance.remetente = self.request.user
        form.instance.usuario = self.request.user
        messages.success(self.request, "Agendamento criado com sucesso!")  # Mensagem de sucesso
        return super().form_valid(form)
    
    
class AgendamentoDetail(LoginRequiredMixin, DetailView):
    model = Agendamento
    template_name = 'agendamentodetail.html'



class AgendamentoDelete(LoginRequiredMixin, DeleteView):
    model = Agendamento
    template_name = 'deleteagendamento.html'
    success_url = reverse_lazy('agendamentos:agendamentos-list')

    def delete(self, request, *args, **kwargs):
        messages.success(request, "Agendamento excluído com sucesso!")  # Mensagem de sucesso
        return super().delete(request, *args, **kwargs)


class AgendamentosUpdateView(LoginRequiredMixin, UpdateView):
    model = Agendamento
    form_class = AgendamentoForm
    template_name = 'agendamentosupdate.html'
    success_url = reverse_lazy('agendamentos:agendamentos-list')


# Registro de Usuário
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Usuário registrado com sucesso!")  # Mensagem de sucesso
            return redirect('home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'register.html', {'form': form})





def logout_view(request):
    auth_logout(request)  # Logout do usuário
    return redirect('home')  # Redireciona para a view 'home'






def prestadores_por_categoria(request, categoria_id):
    categoria = get_object_or_404(Categoria, id=categoria_id)
    prestadores = User.objects.filter(tipo_usuario='prestador', servicos__categoria=categoria).distinct()

    print("Categoria:", categoria)
    print("Prestadores encontrados:", prestadores)

    return render(request, 'prestadores_lista.html', {'prestadores': prestadores, 'categoria': categoria})

user/templates/agendamentodetail.html
{% extends 'base.html' %}
{% block title %}
Detalhes do Agendamento
{% endblock %}
{% block content %}
<br><br><br>
<div class="container mt-5">
    <div class="row mb-4">
        <div class="col-md-12 text-center">
            <h2 class="display-6 text-Black fw-bold">Detalhes do Agendamento</h2>
        </div>
    </div>

    <div class="card shadow-lg border-0">
        <div class="card-header bg-success text-white">
            <h4 class="mb-0">{{ agendamento.servico }}</h4>
        </div>
        <div class="card-body p-4">
            <div class="row mb-3">
                <div class="col-md-6">
                    <p><strong>Data do Agendamento:</strong> {{ agendamento.data }}</p>
                </div>
                <div class="col-md-6">
                    <p><strong>Responsável:</strong> {{ agendamento.remetente }}</p>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-md-6">
                    <p><strong>Status:</strong>
                        <span class="badge 
                            {% if agendamento.status == 'Concluído' %}
                                bg-success
                            {% elif agendamento.status == 'Pendente' %}
                                bg-warning text-dark
                            {% else %}
                                bg-secondary
                            {% endif %}">
                            {{ agendamento.status }}
                        </span>
                    </p>
                </div>
                <div class="col-md-6">
                    <p><strong>Observações:</strong> {{ agendamento.conteudo }}</p>
                </div>
            </div>
        </div>
    </div>

    <a href="{% url 'agendamentos:agendamentos-list' %}" class="btn btn-outline-primary mt-4 float-end">
        <i class="bi bi-arrow-left"></i> Voltar à Lista
    </a>
</div>
{% endblock %}

user/templates/agendamentos.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<br><br><br>
<style>
    h2 {
        text-align: center;
    }
</style>
<div class="container mt-5">
    <div class="container">
        <h2 class="text-Black fw-bold">Meus Agendamentos</h2>
        <a href="{% url 'agendamentos:agendamento-create' %}" class="btn btn-success btn-lg">
            <i class="bi bi-plus"></i> Novo Agendamento
        </a>
    </div>
    <br>
    <div class="card shadow-lg border-0">
        <div class="card-body p-4">
            <div class="table-responsive">
                <table class="table table-striped table-hover align-middle">
                    <thead class="table-dark">
                        <tr>
                            <th>ID</th>
                            <th>Data</th>
                            <th>Usuário</th>
                            <th>Serviço</th>
                            <th>Status</th>
                            <th>Contato</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for agendamento in agendamentos %}
                        <tr>
                            <td>{{ agendamento.id }}</td>
                            <td>{{ agendamento.data }}</td>
                            <td>{{ agendamento.usuario }}</td>
                            <td>{{ agendamento.servico }}</td>
                            <td>
                                <span class="badge 
                                    {% if agendamento.status == 'Concluído' %} 
                                        bg-success 
                                    {% elif agendamento.status == 'Pendente' %} 
                                        bg-warning text-dark 
                                    {% else %} 
                                        bg-secondary 
                                    {% endif %}">
                                    {{ agendamento.status }}
                                </span>
                            </td>
                            <td>{{ agendamento.conteudo }}</td>
                            <td>
                                <a href="{% url 'agendamentos:agendamentodetail' agendamento.id %}"
                                    class="btn btn-info btn-sm" data-bs-toggle="tooltip" title="Visualizar">
                                    <i class="bi bi-eye"></i>
                                </a>
                                <a href="{% url 'agendamentos:agendamentosupdate' agendamento.id %}"
                                    class="btn btn-success btn-sm" data-bs-toggle="tooltip" title="Editar">
                                    <i class="bi bi-pencil"></i>
                                </a>
                                <a href="{% url 'agendamentos:deleteagendamento' agendamento.id %}"
                                    class="btn btn-danger btn-sm" data-bs-toggle="tooltip" title="Excluir">
                                    <i class="bi bi-trash"></i>
                                </a>
                                <a href="{% url 'avaliacao-create' agendamento.servico.id %}"
                                    class="btn btn-warning btn-sm" data-bs-toggle="tooltip" title="Avaliar">
                                    <i class="bi bi-star"></i>
                                </a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="7" class="text-center">Nenhum evento encontrado.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user/templates/agendamentosupdate.html
{% extends "base.html" %}
{% load custom_filters %}
{% load static %}
{% block title %}Editar Agendamentos{% endblock %}
{% block content %}
<br><br><br>
<style>
    h3 {
        text-align: center;
    }
</style>
<div class="container">

    <div class="card">
        <div class="card-body">
            <br>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h3>Editar Agendamento</h3>
                <br><br>
                <div class="container">

                    <div class="row g-4">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="{{ form.data.id_for_label }}" class="form-label">
                                    {{ form.data.label }}
                                </label>
                                {{ form.data|add_class:"form-control" }}
                            </div>
                        </div>
                        <br><br>
    
                        <div class="col-md-6">
                            <div class="form-group">
    
                            </div>
                        </div>
    
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="{{ form.servico.id_for_label }}" class="form-label">
                                    {{ form.servico.label }}
                                </label>
                                {{ form.servico|add_class:"form-control" }}
                            </div>
                        </div>
    
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="{{ form.status.id_for_label }}" class="form-label">
                                    {{ form.status.label }}
                                </label>
                                {{ form.status|add_class:"form-control" }}
                            </div>
                        </div>
    
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="{{ form.destinatario.id_for_label }}" class="form-label">
                                    {{ form.destinatario.label }}
                                </label>
                                {{ form.destinatario|add_class:"form-control" }}
                            </div>
                        </div>
    
    
                        <div class="col-12">
                            <div class="form-group">
                                <label for="{{ form.conteudo.id_for_label }}" class="form-label">
                                    {{ form.conteudo.label }}
                                </label>
                                {{ form.conteudo|add_class:"form-control" }}
                            </div>
                        </div>
                    </div>
                <div class="buttons-container">
                    <button type="submit" class="btn btn-primary">Atualizar</button>
                    <a href="/agendamentos/" class="btn btn-secondary">Cancelar</a>
                </div>
        </div>
        </form>
    </div>
</div>
</div>
{% endblock %}

user/templates/createagendamento.html
{% extends "base.html" %}
{% load custom_filters %}
{% load static %}
{% block title %}Agendamentos{% endblock %}

{% block content %}
<br><br><br>

<div class="container mt-5">
    <div class="card shadow-lg border-0">
        <div class="card-body p-5">
            <h3 class="text-center text-primary fw-bold mb-4">Agendar Serviço <i
                    class="bi bi-person-workspace fs-3"></i></h3>

            <form method="post" enctype="multipart/form-data" action="{% url 'agendamentos:agendamento-create' %}">
                {% csrf_token %}

                <div class="row g-4">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="{{ form.data.id_for_label }}" class="form-label">
                                {{ form.data.label }}
                            </label>
                            {{ form.data|add_class:"form-control" }}
                        </div>
                    </div>
                    <br><br>

                    <div class="col-md-6">
                        <div class="form-group">

                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="{{ form.servico.id_for_label }}" class="form-label">
                                {{ form.servico.label }}
                            </label>
                            {{ form.servico|add_class:"form-control" }}
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="{{ form.status.id_for_label }}" class="form-label">
                                {{ form.status.label }}
                            </label>
                            {{ form.status|add_class:"form-control" }}
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="{{ form.destinatario.id_for_label }}" class="form-label">
                                {{ form.destinatario.label }}
                            </label>
                            {{ form.destinatario|add_class:"form-control" }}
                        </div>
                    </div>


                    <div class="col-12">
                        <div class="form-group">
                            <label for="{{ form.conteudo.id_for_label }}" class="form-label">
                                {{ form.conteudo.label }}
                            </label>
                            {{ form.conteudo|add_class:"form-control" }}
                        </div>
                    </div>
                </div>

                <div class="d-flex justify-content-between mt-4">
                    <button type="submit" class="btn btn-primary btn-lg">
                        <i class="bi bi-calendar-plus"></i> Agendar
                    </button>
                    <a href="/agendamentos/" class="btn btn-secondary btn-lg">
                        <i class="bi bi-x-circle"></i> Cancelar
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

user/templates/deleteagendamento.html
{% extends 'base.html' %}
{% block title %}
Excluir agendamento
{% endblock %}

{% block content %}
<br><br><br><br>
<h2>Excluir Agendamento</h2>
<p>Tem certeza de que deseja excluir?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Confirmar Exclusão</button>
</form>
<a href="/agendamentos/">Cancelar</a>
{% endblock %}

user/templates/novousuario.html
{% extends "base.html" %}

{% load static %}
{% block title %}Novo Usuário{% endblock %}
{% block content %}
<style>
    h1 {
        text-align: center;
    }
</style>
<br><br>
<div class="container-fluid">

    <div class="card">
        <div class="card-body">
            <br>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h1>Novo Usuário</h1>
                <table>
                    {{ form.as_table }}
                </table>
                <div>
                    <div class="buttons-container">
                        <input type="submit" value="Salvar Alterações" class="btn btn-primary">
                        <a href="/usuarios/" class="btn btn-secondary">Cancelar</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

user/templates/prestadores_lista.html
{% extends 'base.html' %}

{% block content %}
<br><br><br><br>
<div class="container">
    <div class="card p-4 shadow-sm">
        <h2 class="mb-4 text-center"><strong>{{ categoria.nome }}</strong></h2>

        <div class="list-group">
            {% for prestador in prestadores %}
            <div class="list-group-item list-group-item-action mb-3 rounded border">
                <h5 class="mb-2">{{ prestador.username }}</h5>
                <p class="mb-1">{{ prestador.email }}</p>
                <p class="mb-1">{{ prestador.telefone }}</p>

                <small class="text-muted d-block mb-2">
                    {% with prestador.servicos.all as servicos %}
                        {% if servicos %}
                            {% for servico in servicos %}
                                <p class="mb-1">
                                    Serviço: {{ servico.nome }} - Média: {{ servico.media_avaliacoes|floatformat:1 }}
                                    <i class="bi bi-star"></i>
                                </p>
                            {% endfor %}
                        {% else %}
                            <p>Nenhum serviço avaliado.</p>
                        {% endif %}
                    {% endwith %}
                </small>

                <a href="{% url 'agendamentos:agendamento-create' prestador.id %}" class="btn btn-primary mt-2">
                    Agendar com {{ prestador.username }}
                </a>
            </div>
            {% empty %}
            <p class="text-center text-muted">Nenhum prestador encontrado nesta categoria.</p>
            {% endfor %}
        </div>
    </div>
    <a href="{% url 'home'%}" class="btn btn-success mt-3">Voltar Para a Home</a>
</div>
{% endblock %}

user/templates/usuarios.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<style>
    h5 {
        text-align: center;
    }
</style>
<br><br><br>

<div class="container-fluid">
    <div class="card">
        <h5>Cadastro de Usuários</h5>
    </div>

    <div class="table-responsive">
        <table class="table table-striped table-dark table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Tipo de Usuário</th>
                    <th>Nome Do Usuário</th>

                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for usuario in usuarios %}
                <tr>
                    <td>{{ usuario.id }}</td>
                    <td>{{ usuario.tipo_usuario }}</td>
                    <td>{{ usuario.username }}</td>


                    <td>
                        <a href="" class="btn btn-info btn-sm">
                            <i class="bi bi-eye"></i>
                        </a>
                        <a href="" class="btn btn-warning btn-sm">
                            <i class="bi bi-pencil"></i>
                        </a>
                        <a href="" class="btn btn-danger btn-sm">
                            <i class="bi bi-trash"></i>
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="8">Nenhum Evento encontrado.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}