master_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from master_project import views
from rest_framework.routers import DefaultRouter
from master.views import ServiceViewSet, AppointmentViewSet, AgendamentoViewSet, UserViewSet
from user.views import prestadores_por_categoria, logout_view
from user import views as user_views
from avaliacao.urls import AvaliacaoCreateView


router = DefaultRouter()
router.register(r'services', ServiceViewSet, basename='service') 
router.register(r'apontamentos', AppointmentViewSet, basename='apontamentos')
router.register(r'agendamentos', AgendamentoViewSet, basename='agendamentos')
router.register(r'usuarios', UserViewSet, basename='usuarios')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('api/', include(router.urls)),
    path('agendamentos/', include('user.urls', namespace='agendamentos')),
    path('avaliacao/', include('avaliacao.urls')),

    
    
    
    # URLs de Login e Logout
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', logout_view, name='logout'),



    # Cadastro de usuário
    path('register/', user_views.register, name='register'),
    path('prestadores/categoria/<int:categoria_id>/', prestadores_por_categoria, name='prestadores_por_categoria'),
    
   
]

user/urls.py
from user.views import AgendamentoCreate,AgendamentosListView, UsuariosListView, Novousuario, AgendamentoDelete, AgendamentoDetail, AgendamentosUpdateView, AgendamentoCreateView
from django.urls import path
 
app_name = 'agendamentos' 
 
urlpatterns = [
 # URLs para Agendamentos
    path('', AgendamentosListView.as_view(), name='agendamentos-list'),
    path('novo/', AgendamentoCreate.as_view(), name='agendamento-create'),
    path('delete/<int:pk>/', AgendamentoDelete.as_view(), name='deleteagendamento'),
    path('<int:pk>/', AgendamentoDetail.as_view(), name='agendamentodetail'),
    path('<int:pk>/editar/', AgendamentosUpdateView.as_view(), name='agendamentosupdate'),
    path('novo/<int:prestador_id>/', AgendamentoCreateView.as_view(), name='agendamento-create'),
    
    
    path('usuarios', UsuariosListView.as_view(), name='usuarios-list'),
    path('usuarios/novo/', Novousuario.as_view(), name='usuario-create'),

    ]

master_project/views.py
from django.shortcuts import render
from master.models import Servicos, Categoria
from avaliacao.models import Avaliacao
from django.contrib.auth.decorators import login_required


def home(request):
    servicos = Servicos.objects.all()
    categorias = Categoria.objects.all()
    print(categorias)
    avaliacoes = Avaliacao.objects.all()
    return render(request, 'home.html',
                  {'servicos': servicos, 
                   'categorias': categorias,
                   'avaliacoes': avaliacoes,
                   })

master_project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br" data-bs-theme="light">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

</head>

<body>
    {% block content %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% include 'home.html' %}
    {% endblock %}

    <style>
        body {
            background-color: #ffffff
        }

        .navbar-nav .nav-link {
            display: flex;
            align-items: center;
            color: #ffffff;
            margin-bottom: 0;


        }

        .navbar-nav .nav-link:hover {
            background-color: #3398af;
            /* Cor do fundo ao passar o mouse */
            border-radius: 5px;
            /* Adiciona um arredondamento ao fundo */

        }

        .navbar-nav .nav-link i {
            margin-right: 4px;
            /* Espaçamento entre o ícone e o texto */

        }

        .navbar-nav .nav-link.active {
            color: #ffdb8e;
            /* Cor do texto para o item ativo */

        }

        .navbar-brand {
            font-size: 14px;

            margin: 0;
        }

        .bi-house {
            color: brown;
        }

        .bi-check-circle {
            color: rgb(149, 205, 209);
        }

        .bi-star {
            color: gold;
        }
    </style>


    <nav class="navbar navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}" style="font-family:'Times New Roman', Times, serif">
                <img src="{% static 'logo.png' %}" alt="Logo" style="height: 20px; margin-right: 7px;">
                MASTER SERVICES
            </a>
            <div class="d-flex flex-grow-1 justify-content-center align-items-center">
                {% if user.is_authenticated %}
                <li class="text-white me-2">Olá, {{ user.username }}</li>
                <a href="{% url 'logout' %}" class="text-white">Logout</a>
                {% else %}
                <a href="{% url 'login' %}" class="text-white me-3">Faça seu Login</a>
                <span class="text-white">ou</span>
                <a href="{% url 'register' %}" class="text-white ms-3">Registre-se</a>
                {% endif %}
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"
                aria-labelledby="offcanvasDarkNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">MASTER SERVICES</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">
                                <i class="bi bi-house fs-3"></i> Home
                            </a>
                        </li>
                        {% if user.is_authenticated %}

                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page"
                                href="{% url 'agendamentos:agendamentos-list' %}">
                                <i class="bi bi-check-circle fs-3"></i> Contrate Serviços
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'avaliacoeslist' %}">
                                <i class="bi bi-star fs-3"></i> Minhas Avaliações
                            </a>
                        </li>
                        {% else %}
                        <p>É necessário Estar Logado para acessar os serviços</p>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels"></script>
</body>

</html>

master_project/templates/footer.html
<style>
    .footer {
        text-align: center;
    }

    .footer ul {
        list-style-type: none;
        padding: 0;
    }

    .footer ul li {
        display: inline;
        margin-right: 10px;
    }

    .footer a {
        text-decoration: none;
    }


    .social-icon.facebook i {
        color: #3b5998;

    }

    .social-icon.twitter i {
        color: #00acee;
    }

    .social-icon.instagram i {
        color: #e4405f;
    }

    .social-icon.linkedin i {
        color: #0e76a8;
    }

    .social-icon:hover i {
        color: #ffb121;
        /* Cor ao passar o mouse */
    }
</style>
<br>
<br>
<br>
<center>
    <footer class="footer">
        <div class="footer-section">
            <h5>Redes Sociais</h5>
            <ul class="social-links">
                <li><a href="#" class="social-icon facebook"><i class="fab fa-facebook-f"></i></a></li>
                <li><a href="#" class="social-icon twitter"><i class="fab fa-twitter"></i></a></li>
                <li><a href="#" class="social-icon instagram"><i class="fab fa-instagram"></i></a></li>
                <li><a href="#" class="social-icon linkedin"><i class="fab fa-linkedin-in"></i></a></li>
            </ul>
        </div>
        <div class="footer-bottom">
            <p>&copy; {{ '2024' }} Master Services. Todos os direitos reservados.</p>
            <p id="dataAcesso">Acesso em:</p>
        </div>
    </footer>
    <script>
        const dataAtual = new Date();
        const options = { year: 'numeric', month: 'long', day: 'numeric' };
        const dataFormatada = dataAtual.toLocaleDateString('pt-BR', options);

        document.getElementById('dataAcesso').textContent = `Acesso em: ${dataFormatada}`;
    </script>
</center>

master_project/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}

<br><br><br><br>
<style>
    .custom-card-header {
        background-color: #18385b;
        /* Cor verde */
        color: white;
        /* Texto branco */
    }

    .custom-card-body {
        background-color: #D4EDDA;
        /* Cor de fundo leve */
    }

    .btn-custom {
        background-color: #18385b;
        color: whitesmoke;
    }

    h4 {
        color: #333333;
    }
</style>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<center>
    <h4>Não tenha mais Dores de Cabeça ao precisar de um Serviço!</h4>
</center>

<br>
<div class="container">
    <div id="carouselExampleCaptions" class="carousel slide">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static '3.jpg' %}" alt="Imagem 1" class="d-block w-100"
                    style="height: 400px; object-fit: none;">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Confiabilidade</h5>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static '1.jpg' %}" alt="Imagem 2" class="d-block w-100"
                    style="height: 400px; object-fit: scale-down;">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Gestão fácil de Serviços</h5>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static '2.jpg' %}" alt="Imagem 3" class="d-block w-100"
                    style="height: 400px; object-fit: none;">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Venha já, Não perca mais tempo!!!</h5>
                    <p>Total Compromisso com a Realização concreta do Serviço</p>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>
<br>

<div class="dropdown">
    <center>
        <button class="btn btn-custom dropdown-toggle btn-lg" type="button" id="dropdownMenuButton"
            data-bs-toggle="dropdown" aria-expanded="false">
            Serviços a Contratar
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            {% if user.is_authenticated %}
                {% for categoria in categorias %}
                    <li>
                        <a class="dropdown-item"
                            href="{% url 'prestadores_por_categoria' categoria.id %}">{{categoria.nome}}</a>
                    </li>
                {% empty %}
                    <li><a class="dropdown-item" href="#">Nenhuma categoria disponível</a></li>
                {% endfor %}
            {% else %}
                <li class="dropdown-item text-danger">Necessário estar logado</li>
            {% endif %}
        </ul>
    </center>
</div>

</div>
<div class="container mt-4">
    <div class="card">
        <div class="card-header custom-card-header">
            <h5>Melhores Avaliados:</h5>
        </div>
        <div class="card-body custom-card-body">
            {% for servico in servicos %}
            <div class="mb-3 border rounded p-3 shadow-sm">
                <h4>{{ servico.prestador }}</h4>
                <h6 class="mb-1">{{ servico.nome }}</h6>
                <p class="mb-1">
                    Média: {{ servico.media_avaliacoes|floatformat:1 }}
                    <i class="bi bi-star"></i>
                </p>
                <small class="text-muted">Especialidade: {{ servico.especialidade }}</small>
            </div>
            {% empty %}
            <p>Nenhum serviço avaliado.</p>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

master_project/templates/login.html
<!-- templates/login.html -->

{% extends "base.html" %}
{% load static %}
{% block content %}
<br><br><br><br>

<center>
    <h2>Login</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Entrar</button>
    </form>
</center>
{% endblock %}

master_project/templates/register.html
<!-- templates/register.html -->

{% extends "base.html" %}
{% load static %}

{% block content %}
<br><br><br>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header text-center">
                    <h2>Registro</h2>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Nome de Usuário:</label>
                            <input type="text" name="username" class="form-control" id="id_username" required>
                            {% if form.username.errors %}
                            <div class="text-danger">{{ form.username.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <label for="id_email" class="form-label">Email:</label>
                            <input type="email" name="email" class="form-control" id="id_email" required>
                            {% if form.email.errors %}
                            <div class="text-danger">{{ form.email.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <label for="id_password1" class="form-label">Senha:</label>
                            <input type="password" name="password1" class="form-control" id="id_password1" required>
                            {% if form.password1.errors %}
                            <div class="text-danger">{{ form.password1.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <label for="id_password2" class="form-label">Confirme a Senha:</label>
                            <input type="password" name="password2" class="form-control" id="id_password2" required>
                            {% if form.password2.errors %}
                            <div class="text-danger">{{ form.password2.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <label for="tipo_usuario" class="form-label">Tipo de Usuário</label>
                            <select name="tipo_usuario" id="tipo_usuario" class="form-control" required>
                                <option value="">Selecione</option>
                                <option value="prestador">Prestador</option>
                                <option value="cliente">Cliente</option>
                            </select>
                            {{ form.tipo_usuario.errors }}
                        </div>
                        <div class="mb-3">
                            <label for="foto" class="form-label">Foto</label>
                            {{ form.foto }}
                            {{ form.foto.errors }}
                        </div>

                        <!-- Campos para prestadores -->
                        <div id="prestador-fields" style="display: none;">
                            <div class="mb-3">
                                <label for="titulo_servico" class="form-label">Título do Serviço</label>
                                <input type="text" name="titulo_servico" class="form-control"
                                    placeholder="Título do Serviço" />
                            </div>
                            <div class="mb-3">
                                <label for="categoria_servico" class="form-label">Categoria</label>
                                {{ form.categoria_servico }}
                                {{ form.categoria_servico.errors }}
                            </div>
                            <div class="mb-3">
                                <label for="grupo_servico" class="form-label">Grupo</label>
                                {{ form.grupo_servico }}
                                {{ form.grupo_servico.errors }}
                            </div>
                            <div class="mb-3">
                                <label for="especialidade_servico" class="form-label">Especialidade</label>
                                {{ form.especialidade_servico }}
                                {{ form.especialidade_servico.errors }}
                            </div>
                        </div>


                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Registrar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const tipoUsuarioSelect = document.getElementById('tipo_usuario');
        const prestadorFields = document.getElementById('prestador-fields');

        console.log(tipoUsuarioSelect); // Verifique se o elemento está presente

        if (tipoUsuarioSelect) { // Verifica se o elemento foi encontrado
            tipoUsuarioSelect.addEventListener('change', function () {
                if (this.value === 'prestador') {
                    prestadorFields.style.display = 'block';
                } else {
                    prestadorFields.style.display = 'none';
                }
            });
        } else {
            console.error('Elemento tipo_usuario não encontrado.');
        }
    });
</script>

{% endblock %}